{{- if not .Values.manager.certificates.certManagement.issuer }}
---
apiVersion: v1
kind: Secret
metadata:
  name: issuer-ca-secret
  namespace: {{.Release.Namespace}}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.manager.certificates.certManagement.crt }}
  tls.key: {{ .Values.manager.certificates.certManagement.key }}
{{- end}}
