{{- $cn := printf "sap-btp-operator-webhook-service"  }}
{{- $ca := genCA (printf "%s-%s" $cn "ca") 3650 }}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}
{{- if not .Values.manager.certificates }}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  namespace: {{.Release.Namespace}}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sap-btp-service-operator-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
---
{{- end}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  {{- if .Values.manager.certificates.certManager }}
  annotations:
    cert-manager.io/inject-ca-from: {{.Release.Namespace}}/sap-btp-operator-serving-cert
  {{- end}}
  name: sap-btp-operator-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        name: sap-btp-operator-webhook-service
        namespace: {{.Release.Namespace}}
        path: /mutate-services-cloud-sap-com-v1-servicebinding
      {{- if not .Values.manager.certificates }}
      caBundle: {{ b64enc $ca.Cert }}
      {{- end }}
      {{- if .Values.manager.certificates.selfSigned }}
      caBundle: {{.Values.manager.certificates.selfSigned.caBundle }}
      {{- end }}
      {{- if .Values.manager.certificates.gardenerCertManager }}
      caBundle: {{.Values.manager.certificates.gardenerCertManager.caBundle }}
      {{- end }}
    failurePolicy: Fail
    name: mservicebinding.kb.io
    rules:
      - apiGroups:
          - services.cloud.sap.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - servicebindings
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        name: sap-btp-operator-webhook-service
        namespace: {{.Release.Namespace}}
        path: /mutate-services-cloud-sap-com-v1-serviceinstance
      {{- if not .Values.manager.certificates }}
      caBundle: {{ b64enc $ca.Cert }}
      {{- end }}
      {{- if .Values.manager.certificates.selfSigned }}
      caBundle: {{.Values.manager.certificates.selfSigned.caBundle }}
      {{- end }}
      {{- if .Values.manager.certificates.gardenerCertManager }}
      caBundle: {{.Values.manager.certificates.gardenerCertManager.caBundle }}
      {{- end }}
    failurePolicy: Fail
    name: mserviceinstance.kb.io
    rules:
      - apiGroups:
          - services.cloud.sap.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - serviceinstances
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  {{- if .Values.manager.certificates.certManager }}
  annotations:
    cert-manager.io/inject-ca-from: {{.Release.Namespace}}/sap-btp-operator-serving-cert
  {{- end}}
  name: sap-btp-operator-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        name: sap-btp-operator-webhook-service
        namespace: {{.Release.Namespace}}
        path: /validate-services-cloud-sap-com-v1-servicebinding
      {{- if not .Values.manager.certificates }}
      caBundle: {{ b64enc $ca.Cert }}
      {{- end }}
      {{- if .Values.manager.certificates.selfSigned }}
      caBundle: {{.Values.manager.certificates.selfSigned.caBundle }}
      {{- end }}
      {{- if .Values.manager.certificates.gardenerCertManager }}
      caBundle: {{.Values.manager.certificates.gardenerCertManager.caBundle }}
      {{- end }}
    failurePolicy: Fail
    name: vservicebinding.kb.io
    rules:
      - apiGroups:
          - services.cloud.sap.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - servicebindings
    sideEffects: None