name: Release SAPBTP Operator
on:
  release:
    types: [published]
jobs:
  release:
    name: Release SAPBTP Operator
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.event.release.tag_name }}
      CHART_URL: https://github.com/SAP/sap-btp-service-operator/releases/download/${{ github.event.release.tag_name }}/sapbtp-operator-${{ github.event.release.tag_name }}.tgz
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build + Push Image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.OPERATOR_USER }}
          password: ${{ secrets.OPERATOR_PAT }}
          registry: ghcr.io
          repository: SAP/sap-btp-service-operator/controller
          tag_with_ref: true

      - name: Install kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: 3.1.0

      - name: Prepare SAPBTP Operator charts
        run: make helm-charts

      - name: Install helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        run: |
          sed -i -e 's/tag: master/tag: '${TAG_NAME:-master}'/g' ./sapcp-operator-charts/values.yaml | sh
          mkdir out
          helm package --app-version ${TAG_NAME} --version ${TAG_NAME} -d ./out sapcp-operator-charts
          mv ./hack/kubectl-sapbtp ./out/kubectl-sapbtp

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
          file_glob: true


